# Generated by Django 4.0 on 2024-10-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='text_handler/', verbose_name='Обрабатываемый документ')),
                ('name', models.CharField(max_length=50, verbose_name='Название документа')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, verbose_name='Слово')),
                ('count', models.IntegerField(default=1, verbose_name='Количество слов в тексте')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='text_handler.document', verbose_name='Документ')),
            ],
        ),
    ]
